# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:41
from __future__ import unicode_literals

import carte_interactive.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', storage=carte_interactive.storage.OverwriteStorage(), upload_to='.')),
            ],
        ),
    ]
