# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='nom_court',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
