# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='particularites',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
