# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0001_initial'),
    ]

    operations = [
    ]
