# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0002_ecole_particularites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecole',
            old_name='type_ecole',
            new_name='type',
        ),
    ]
