# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0004_auto_20160520_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
