# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0005_ecole_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='longitude',
        ),
    ]
