# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0006_auto_20160524_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='visite',
            field=models.BooleanField(default=False),
        ),
    ]
