# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0007_ecole_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
