# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0008_ecole_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='nom_court',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
