# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0009_ecole_nom_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='programmes',
        ),
        migrations.AddField(
            model_name='ecole',
            name='programmes_partenaires',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='programmes_uqac',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='particularites',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ville',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
