# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_interactive', '0011_auto_20160622_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='visite_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
